[theme]
primaryColor = "#4299e1"
backgroundColor = "#f7fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a202c"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false